openapi: 3.0.3
info:
  title: SuiDouBashi - OpenAPI 3.0
  description: |-
    SuiDouBashi on the OpenAPI 3.0 specification.
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://fullnode.mainnet.sui.io:443
  - url: https://fullnode.devnet.sui.io:443
  - url: http://127.0.0.1:9000
tags:
  - name: pool_reg
    description: Pools Governance
  - name: pool
    description: Liquidity pool
  - name: LP
    description: Liqudiity Provider Position
paths:
  /pool_reg/{poolReg_id}:
    get:
      tags:
        - pool_reg
      summary: Get Pool Registry Object
      description: Get Pool Registry Object
      parameters:
        - name: PoolReg id
          in: query
          description: Liqudity Provider Position
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PoolReg"
  /pool_reg/create_pool:
    post:
      tags:
        - pool_reg
      summary: Create a pool
      description: Create a pool by 2 coin types
      requestBody:
        description: Create a pool by 2 coin types
        content:
          application/json:
            schema:
              type: object
              properties:
                  pool_reg:
                    type: string
                  stable:
                    type: boolean
                  metadata_x:
                    type: string
                  metadata_y:
                    type: string
                  fee_percentage:
                    type: integer
                    format: int32
        required: true
      responses:
        '200':
          description: Pool Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  pool_id:
                    type: string
                  creaor:
                    type: string
# Pool
  /pool/add_liquidity:
    put:
      tags:
        - pool
      summary: Add liquidity to pool
      description: Deposit pair of coins to pool
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  pool:
                    type: string
                  coin_x:
                    type: string
                  coin_y:
                    type: string
                  lp:
                    type: string
                  deposit_x_min:
                    type: integer
                    format: int64
                  deposit_y_min:
                    type: integer
                    format: int64
                  clock:
                    type: string
        required: true
      responses:
        '200':
          description: LiquidityAdded
          content:
            application/json:
              schema:
                type: object
                properties:
                  deposit_x:
                    type: integer
                    format: int64
                  deposit_y:
                    type: integer
                    format: int64
                  lp_token:
                    type: integer
                    format: int64
  /pool/remove_liquidity:
    put:
      tags:
        - pool
      summary: Remove liquidity to pool
      description: Withdraw pair of coins to pool
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  pool:
                    type: string
                  coin_y:
                    type: string
                  lp:
                    type: string
                  value:
                    type: integer
                    format: int64
                  withdrawl_x_min:
                    type: integer
                    format: int64
                  withdrawl_y_min:
                    type: integer
                    format: int64
                  clock:
                    type: string
        required: true
      responses:
        '200':
          description: LiquidityRemoved
          content:
            application/json:
              schema:
                type: object
                properties:
                  withdrawl_x:
                    type: integer
                    format: int64
                  withdrawl_y:
                    type: integer
                    format: int64
                  lp_token:
                    type: integer
                    format: int64
  /pool/zap/zap_x:
    put:
      tags:
        - pool
      summary: Add Single liquidity X to pool
      description: Add Single liquidity X to pool
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  pool:
                    type: string
                  coin_x:
                    type: string
                  lp:
                    type: string
                  deposit_x_min:
                    type: integer
                    format: int64
                  deposit_y_min:
                    type: integer
                    format: int64
                  clock:
                    type: string
        required: true
      responses:
        '200':
          description: LiquidityAdded
          content:
            application/json:
              schema:
                type: object
                properties:
                  swap:
                    type: object
                    properties:
                      input:
                        type: integer
                        format: int64
                      output:
                        type: integer
                        format: int64
                  liqudiityAdded:
                    type: object
                    properties:
                      deposit_x:
                        type: integer
                        format: int64
                      deposit_y:
                        type: integer
                        format: int64
                      lp_token:
                        type: integer
                        format: int64
  /pool/zap/zap_y:
    put:
      tags:
        - pool
      summary: Add Single liquidity Y to pool
      description: Add Single liquidity Y to pool
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  pool:
                    type: string
                  coin_y:
                    type: string
                  lp:
                    type: string
                  deposit_x_min:
                    type: integer
                    format: int64
                  deposit_y_min:
                    type: integer
                    format: int64
                  clock:
                    type: string
        required: true
      responses:
        '200':
          description: LiquidityAdded
          content:
            application/json:
              schema:
                type: object
                properties:
                  swap:
                    type: object
                    properties:
                      input:
                        type: integer
                        format: int64
                      output:
                        type: integer
                        format: int64
                  liqudiityAdded:
                    type: object
                    properties:
                      deposit_x:
                        type: integer
                        format: int64
                      deposit_y:
                        type: integer
                        format: int64
                      lp_token:
                        type: integer
                        format: int64
  /pool/swap/swap_for_x:
    put:
      tags:
        - pool
      summary: Swap coin X for coin Y
      description: Swap coin X for coin Y
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  pool:
                    type: string
                  coin_x:
                    type: string
                  output_y_min:
                    type: integer
                    format: int64
                  clock:
                    type: string
        required: true
      responses:
        '200':
          description: Swap
          content:
            application/json:
              schema:
                type: object
                properties:
                  input:
                    type: integer
                    format: int64
                  output:
                    type: integer
                    format: int64
  /pool/swap/swap_for_y:
    put:
      tags:
        - pool
      summary: Swap coin Y for coin X
      description: Swap coin Y for coin X
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  pool:
                    type: string
                  coin_y:
                    type: string
                  output_x_min:
                    type: integer
                    format: int64
                  clock:
                    type: string
        required: true
      responses:
        '200':
          description: Swap
          content:
            application/json:
              schema:
                type: object
                properties:
                  input:
                    type: integer
                    format: int64
                  output:
                    type: integer
                    format: int64
  /pool/{pool_id}:
    get:
      tags:
        - pool
      summary: Get Pool Object
      description: Get Pool Object
      parameters:
        - name: Pool
          in: query
          description: Get Pool Object
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pool"
  /pool/get_output:
    get:
      tags:
        - pool
      summary: Get optimized output by input X & type X
      description: Get LP's reward X
      parameters:
        - name: Pool
          in: query
          description: Optimized output Y by given inupt X
          required: true
          explode: true
          schema:
            type: string
        - name: type
          in: query
          description: type of input X
          required: true
          explode: true
          schema:
            type: string
        - name: value
          in: query
          description: value of input X
          required: true
          explode: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: integer
                format: int64
# LP
  /lp/create_lp:
    post:
      tags:
        - LP
      summary: Create a LP position
      description: Create a LP position
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  pool:
                    type: string
        required: true
      responses:
        '200':
          description: Swap
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LP"
  /lp/join_lp:
    put:
      tags:
        - LP
      summary: Join one LP position to another
      description: Combine two LP position
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  pool:
                    type: string
                  payee_lp:
                    type: string
                  payer_lp:
                    type: string
                  value:
                    type: integer
                    format: int64
        required: true
      responses:
        '200':
          description: Swap
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LP"
  /lp/delete_lp:
    delete:
      tags:
        - LP
      summary: Delete empty LP position
      description: Delete empty LP position
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  lp:
                    type: string
        required: true
      responses:
        '200':
          description: Swap
          content:
            application/json:
              schema:
              # no response since we have already know this is empty
                $ref: "#/components/schemas/LP"
  /lp/{lp_id}:
    get:
      tags:
        - LP
      summary: Get LP information
      description: Get LP information
      parameters:
        - name: LP
          in: query
          description: Liqudity Provider Position
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LP"
  /lp/get_claimable_x:
    get:
      tags:
        - LP
      summary: Get LP's reward X
      description: Get LP's reward X
      parameters:
        - name: LP
          in: query
          description: Liqudity Provider Position
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: integer
                format: int64
  /lp/get_claimable_y:
    get:
      tags:
        - LP
      summary: Get LP's reward Y
      description: Get LP's reward Y
      parameters:
        - name: LP
          in: query
          description: Liqudity Provider Position
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: integer
                format: int64

components:
  schemas:
    PoolReg:
      type: object
      properties:
        id:
          type: string
          example: "0x0b3fc768f8bb3c772321e3e7781cac4a45585b4bc64043686beb634d65341798"
        pools:
          type: array
          items:
            type: string
            example: "0x0b3fc768f8bb3c772321e3e7781cac4a45585b4bc64043686beb634d65341798"
            additionalProperties:
              type: string
        guardian:
          type: string
          example: "0x0b3fc768f8bb3c772321e3e7781cac4a45585b4bc64043686beb634d65341798"
      xml:
        name: order
    Pool:
      type: object
      properties:
        id:
          type: string
          example: "0x0b3fc768f8bb3c772321e3e7781cac4a45585b4bc64043686beb634d65341798"
        type_x:
          type: string
          example: "0x0b3fc768f8bb3c772321e3e7781cac4a45585b4bc64043686beb634d65341798::usdc::USDC"
        type_y:
          type: string
          example: "0x0b3fc768f8bb3c772321e3e7781cac4a45585b4bc64043686beb634d65341798::usdt::USDT"
        stable:
          type: boolean
        locked:
          type: boolean
        lp_supply:
          type: integer
          format: int64
        reserve_x:
          type: integer
          format: int64
        reserve_y:
          type: integer
          format: int64
        reserve_lp:
          type: integer
          format: int64
        decimals_x:
          type: integer
          format: int32
        decimals_y:
          type: integer
          format: int32
        last_block_timestamp:
          type: integer
          format: int64
        last_price_x_cumulative:
          type: integer
          format: int64
        last_price_y_cumulative:
          type: integer
          format: int64
        observations:
          type: array
          items:
            $ref: "#/components/schemas/Observation"
        fee:
          type: object
          properties:
            fee_x:
              type: integer
              format: int64
            fee_y:
              type: integer
              format: int64
            index_x:
              type: integer
              format: int64
            index_y:
              type: integer
              format: int64
            fee_percentage:
              type: integer
              format: int32
    Observation:
      type: object
      properties:
        timestamp:
          type: integer
          format: int64
        reserve_x_cumulative:
          type: integer
          format: int64
        reserve_y_cumulative:
          type: integer
          format: int64
    LP:
      type: object
      properties:
        id:
          type: string
        lp_balance:
          type: integer
          format: int64
        index_x:
          type: integer
          format: int64
        index_y:
          type: integer
          format: int64
        claimable_x:
          type: integer
          format: int64
        claimable_y:
          type: integer
          format: int64
