[package]
name = "suiDouBashiVSDB"
version = "0.0.1"
published-at = "0x5335303848afc75af4887d64929283e580ed91b996fd2d4d61ebae243df822c3"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir="crates/sui-framework/packages/sui-framework/", rev = "testnet" }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir="crates/sui-framework/packages/move-stdlib/", rev = "testnet" }
SuiSystem = { git = "https://github.com/MystenLabs/sui.git", subdir="crates/sui-framework/packages/sui-system/", rev = "testnet" }

[addresses]
 suiDouBashi_vsdb = "0x5335303848afc75af4887d64929283e580ed91b996fd2d4d61ebae243df822c3"
